apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pg-logs
  namespace: storedog
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn 