services:
  frontend:
    # image: ghcr.io/datadog/storedog/frontend:${STOREDOG_IMAGE_VERSION:-latest}
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      target: development
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 3s
      start_period: 60s
    ports:
      - '3000:3000'
    networks:
      - storedog-network
    environment:
      - DD_AGENT_HOST=dd-agent
      - DD_ENV=${DD_ENV:-production}
      - DD_PROFILING_ENABLED=true
      - DD_PROFILING_TIMELINE_ENABLED=true
      - DD_PROFILING_ALLOCATION_ENABLED=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_SERVICE=${NEXT_PUBLIC_DD_SERVICE_FRONTEND:-store-frontend}
      - DD_VERSION=${NEXT_PUBLIC_DD_VERSION_FRONTEND:-1.0.0}
      - NEXT_PUBLIC_DD_ENV=${NEXT_PUBLIC_DD_ENV:-production}
      - NEXT_PUBLIC_DD_VERSION_FRONTEND=${NEXT_PUBLIC_DD_VERSION_FRONTEND:-1.0.0}
      - NEXT_PUBLIC_DD_SERVICE_FRONTEND=${NEXT_PUBLIC_DD_SERVICE_FRONTEND:-store-frontend}
      - NEXT_PUBLIC_DD_SITE=${NEXT_PUBLIC_DD_SITE:-datadoghq.com}
      - NEXT_PUBLIC_DD_APPLICATION_ID=${NEXT_PUBLIC_DD_APPLICATION_ID:-not-set-in-docker-compose}
      - NEXT_PUBLIC_DD_CLIENT_TOKEN=${NEXT_PUBLIC_DD_CLIENT_TOKEN:-not-set-in-docker-compose}
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "auto_multi_line_detection": true }]'
  service-proxy:
    image: ghcr.io/datadog/storedog/nginx:${STOREDOG_IMAGE_VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81/nginx_status/"]
      interval: 3s
      start_period: 30s
    ports:
      - '80:80'
    networks:
      - storedog-network
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      - DD_AGENT_HOST=dd-agent
      - DD_ENV=${DD_ENV:-production}
      - DD_SERVICE=service-proxy
      - DD_VERSION=${DD_VERSION_NGINX:-1.28.0}
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx"}]'
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status/"}]'
  puppeteer:
    # image: ghcr.io/datadog/storedog/puppeteer:${STOREDOG_IMAGE_VERSION:-latest}
    build:
      context: ./services/puppeteer
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - STOREDOG_URL=${STOREDOG_URL:-http://service-proxy:80}
      - PUPPETEER_TIMEOUT=${PUPPETEER_TIMEOUT:-30000}
      - PUPPETEER_ENABLE_CACHE=${PUPPETEER_ENABLE_CACHE:-false}
      - PUPPETEER_MAX_CONCURRENT=${PUPPETEER_MAX_CONCURRENT:-16}
      - PUPPETEER_BROWSER_POOL_SIZE=${PUPPETEER_BROWSER_POOL_SIZE}
      - PUPPETEER_SYSTEM_MEMORY=${PUPPETEER_SYSTEM_MEMORY:-8GB}
      - PUPPETEER_STARTUP_DELAY=${PUPPETEER_STARTUP_DELAY:-10000}
      - PUPPETEER_RAMP_INTERVAL=${PUPPETEER_RAMP_INTERVAL:-30000}
      - PUPPETEER_DEBUG=${PUPPETEER_DEBUG:-false}
      - PUPPETEER_DEBUG_SESSIONS=${PUPPETEER_DEBUG_SESSIONS:-false}
      - PUPPETEER_LOOP=${PUPPETEER_LOOP:-infinite}
      - PUPPETEER_SESSION_TYPES=${PUPPETEER_SESSION_TYPES:-browsing,vip,frustration,homepage,short,taxonomy}
    networks:
      - storedog-network
    depends_on:
      frontend:
        condition: service_healthy
    shm_size: '4gb' # Increase shared memory size
    cap_add:
      - 'SYS_ADMIN' # Required for Puppeteer to run in Docker

networks:
  storedog-network: # Main application network
