services:
  emailer:
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-consumer:${CONSUMER_VERSION}
    ports:
      - 8092:8080
    environment:
      - KAFKA_CONSUME_SERVER=kafka:9092
      # - KAFKA_PRODUCE_SERVER=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_IN=notifications
      - CONSUMER_GROUP=authenticator
      - ENABLE_CRASHES=false
      - CRASH_START_MIN=-1
      - CRASH_END_MIN=-1
      - OUT_MSG_MULTIPLIER=1
      - OUT_MSG_MULTIPLIER_START_MIN=0
      - OUT_MSG_MULTIPLIER_END_MIN=0
      - OUT_MSG_SIZE_CHARS=0
      - HASH=""
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=emailer
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: notifications & kafka (java client)
      # with below, there's only 1 entry in service catalog: notifications
      - DD_SERVICE_MAPPING=kafka:emailer
  authenticator:
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-consumer:${CONSUMER_VERSION}
    ports:
      - 8081:8080
    environment:
      ###################
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - KAFKA_CONSUME_SERVER=kafka:9092
      - KAFKA_PRODUCE_SERVER=kafka:9092
      - KAFKA_CONSUMER_FETCH_MIN_BYTES=50000  # Increase fetch size
      - KAFKA_CONSUMER_FETCH_MAX_WAIT_MS=500 
      # read the code to understand how to use this.
      - TOPICS_IN=human-orders,algo-orders
      - TOPICS_OUT=authenticated-order,suspicious-activity
      - CONSUMER_GROUP=authenticator
      - ENABLE_CRASHES=false
      - CRASH_START_MIN=-1
      - CRASH_END_MIN=-1
      - OUT_MSG_MULTIPLIER=10
      - OUT_MSG_MULTIPLIER_START_MIN=1
      - OUT_MSG_MULTIPLIER_END_MIN=59
      - OUT_MSG_SIZE_CHARS=40
      - HASH=""
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=authenticator
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: notifications & kafka (java client)
      # with below, there's only 1 entry in service catalog: notifications
      - DD_SERVICE_MAPPING=kafka:authenticator
      
  fraud-checker:
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-consumer:${CONSUMER_VERSION}
    ports:
      - 8091:8080
    environment:
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - KAFKA_CONSUME_SERVER=kafka:9092
      - KAFKA_PRODUCE_SERVER=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_IN=suspicious-activity
      - TOPICS_OUT=notifications
      - CONSUMER_GROUP=fraud-checker
      - ENABLE_CRASHES=false
      - CRASH_START_MIN=-1
      - CRASH_END_MIN=-1
      - OUT_MSG_MULTIPLIER=1
      - OUT_MSG_MULTIPLIER_START_MIN=0
      - OUT_MSG_MULTIPLIER_END_MIN=0
      - OUT_MSG_SIZE_CHARS=0
      - HASH=""
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=fraud-checker
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: notifications & kafka (java client)
      # with below, there's only 1 entry in service catalog: notifications
      - DD_SERVICE_MAPPING=kafka:fraud-checker
  balance-checker:
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-consumer:${CONSUMER_VERSION}
    ports:
      - 8087:8080
    environment:
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - KAFKA_CONSUME_SERVER=kafka:9092
      - KAFKA_PRODUCE_SERVER=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_IN=authenticated-order
      - TOPICS_OUT=executable
      - CONSUMER_GROUP=balance-checker
      - ENABLE_CRASHES=false
      - CRASH_START_MIN=-1
      - CRASH_END_MIN=-1
      - OUT_MSG_MULTIPLIER=1
      - OUT_MSG_MULTIPLIER_START_MIN=0
      - OUT_MSG_MULTIPLIER_END_MIN=0
      - OUT_MSG_SIZE_CHARS=0
      - HASH=""
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=balance-checker
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: balance-checker & kafka (java client)
      # with below, there's only 1 entry in service catalog: balance-checker
      - DD_SERVICE_MAPPING=kafka:balance-checker
  trade-excecuted:
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-consumer:${CONSUMER_VERSION}
    ports:
      - 8086:8080
    environment:
      ###################
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - KAFKA_CONSUME_SERVER=kafka:9092
      - KAFKA_PRODUCE_SERVER=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_IN=executable
      #- TOPICS_OUT=","
      - CONSUMER_GROUP=trade-executed
      - ENABLE_CRASHES=false
      - CRASH_START_MIN=-1
      - CRASH_END_MIN=-1
      - OUT_MSG_MULTIPLIER=1
      - OUT_MSG_MULTIPLIER_START_MIN=0
      - OUT_MSG_MULTIPLIER_END_MIN=0
      - OUT_MSG_SIZE_CHARS=0
      - HASH=""
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=trade-executed
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: dsm-kafka-java-consumer & kafka (java client)
      # with below, there's only 1 entry in service catalog: dsm-kafka-java-consumer
      - DD_SERVICE_MAPPING=kafka:trade-executed

  trade-server:
    depends_on:
      - kafka
      - datadog
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-producer:${PRODUCER_VERSION}
    ports:
      - 8082:8080
    environment:
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - BOOTSTRAP=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_OUT=human-orders
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=trade-server
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: dsm-kafka-java-producer & kafka (java client)
      # with below, there's only 1 entry in service catalog: dsm-kafka-java-producer
      - DD_SERVICE_MAPPING=kafka:trade-server
  trade-scheduler:
    depends_on:
      - kafka
      - datadog
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-producer:${PRODUCER_VERSION}
    ports:
      - 8084:8080
    environment:
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - BOOTSTRAP=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_OUT=algo-orders
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=trade-scheduler
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: dsm-kafka-java-producer & kafka (java client)
      # with below, there's only 1 entry in service catalog: dsm-kafka-java-producer
      - DD_SERVICE_MAPPING=kafka:trade-scheduler
  market-watch:
    depends_on:
      - kafka
      - datadog
    image: ${BASE_IMAGE_URL}/shopist-dsm-kafka-producer:${PRODUCER_VERSION}
    ports:
      - 8089:8080
    environment:
      # the 'kafka' hostname must match the 'hostname' in the kafka service section.
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - BOOTSTRAP=kafka:9092
      # read the code to understand how to use this.
      - TOPICS_OUT=algo-orders
      # datadog
      - DD_AGENT_HOST=datadog
      - DD_DATA_STREAMS_ENABLED=true
      - DD_SERVICE_NAME=market-watcher
      - DD_VERSION=0.0.1
      - DD_ENV=dsm-course
      # without below, there's 2 entries in service catalog: dsm-kafka-java-producer & kafka (java client)
      # with below, there's only 1 entry in service catalog: dsm-kafka-java-producer
      - DD_SERVICE_MAPPING=kafka:market-watcher

  kafka:
    hostname: kafka
    image: bitnamilegacy/kafka:3.4.1
    ports:
      - 9092:9092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # see https://github.com/bitnami/containers/tree/main/bitnami/kafka#readme
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - JMX_PORT=9999
      - JAVA_OPTS= |-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Djava.rmi.server.hostname=%%host%%
    labels:
      com.datadoghq.ad.check_names: '["kafka", "kafka_consumer"]'
      com.datadoghq.ad.init_configs: '[{},{}]'
      com.datadoghq.ad.instances: '[[{"host": "%%host%%","port":"9999"}], [{"kafka_connect_str": "%%host%%:9092","monitor_unlisted_consumer_groups":"true"}]]'

  # comment/uncomment this as needed.
  datadog:
    image: gcr.io/datadoghq/agent:7.53.0
    environment:
      - DD_API_KEY
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    ports:
      - "8126:8126/tcp"
      - "8125:8125/udp"
    volumes:
      - /opt/datadog/apm:/opt/datadog/apm
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined
volumes:
  kafka_data:
    driver: local
