receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
  resource:
    attributes:
      - key: deployment.environment
        value: "otel-course"
        action: upsert
exporters:
  debug:
    verbosity: detailed
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]