AllCops:
  # Default formatter will be used if no `-f/--format` option is given.
  DefaultFormatter: progress

  # Enables the result cache if `true`. Can be overridden by the `--cache` command
  # line option.
  UseCache: true

  TargetRubyVersion: 2.7

  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - vendor/bundle/**/*
    - app/javascript/**/*
    - node_modules/**/*
    - config/**/*
    - bin/**/*

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

AlignParameters:
  Enabled: false

ClassLength:
  CountComments: false
  Max: 150

ModuleLength:
  CountComments: false
  Max: 250

Documentation:
  Enabled: false

LineLength:
  Max: 150

MethodLength:
  CountComments: false
  Max: 50

BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'
    - '**/*_spec.rb'
    - 'spec/factories/**/*'

Metrics/AbcSize:
  Max: 45

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Exclude:
    - '**/*controller.rb'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false
