version: "3"
virtualmachines:
  - name: control-plane
    image: datadog-community/monitoring-kubernetes-mono-image-1-0-0
    shell: /bin/bash
    machine_type: n2-standard-2 # 2 vCPUs, 8GB memory
  - name: worker
    image: datadog-community/monitoring-kubernetes-mono-image-1-0-0
    shell: /bin/bash
    machine_type: n2-standard-2 # 2 vCPUs, 8GB memory
    environment:
      K8S_NODE_ROLE: worker
    allow_external_ingress:
      - http
      - https
      - high-ports