apiVersion: v1
kind: ConfigMap
metadata:
  name: dbm-scripts
  namespace: fake-traffic
data:
  dbm_query_one.sh: |
    #!/bin/sh
    set -f
    QUERY="BEGIN; LOCK TABLE items IN EXCLUSIVE MODE;"
    UPDATE_QUERY=$(cat <<EOF
      UPDATE items 
      SET order_count = order_count::int + 1
      WHERE id = (SELECT id FROM items WHERE order_count::int > random() * 7000 LIMIT 1);
      SELECT pg_sleep(1);
    EOF
    )
    for i in {1..15}
    do
      for j in {1..20}
      do
        QUERY="$QUERY$UPDATE_QUERY"
      done
      QUERY="$QUERY COMMIT;"
      PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d postgres -h "$FAKETRAFFIC_POSTGRES_HOST" -c "$QUERY"
      QUERY="BEGIN; LOCK TABLE items IN EXCLUSIVE MODE;" # Reset for next iteration
    done
  dbm_query_two.sh: |
    #!/bin/sh
    set -f
    QUERY="BEGIN; LOCK TABLE items IN EXCLUSIVE MODE;"
    UPDATE_QUERY=$(cat <<EOF
    UPDATE items
    SET order_count = floor(random() * 7000), last_hour = CURRENT_TIMESTAMP
    WHERE id = (SELECT id FROM items WHERE order_count::int > random() * 7000 ORDER BY RANDOM() LIMIT 1);
    EOF
    )
    for i in {1..15}
    do
      for j in {1..20}
      do
        QUERY="$QUERY$UPDATE_QUERY"
      done
      QUERY="$QUERY COMMIT;"
      PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d postgres -h "$FAKETRAFFIC_POSTGRES_HOST" -c "$QUERY"
      QUERY="BEGIN; LOCK TABLE items IN EXCLUSIVE MODE;" # Reset for next iteration
    done
