apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbm-query-one
  namespace: fake-traffic
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            ad.datadoghq.com/dbm-query-one.logs: '[{"source": "postgresql", "service": "cronjob"}]'
        spec:
          containers:
          - name: dbm-query-one
            image: ${REGISTRY_URL}/postgres:${SD_TAG}
            command: ["/bin/sh", "/scripts/dbm_query_one.sh"]
            envFrom:
              - configMapRef:
                  name: storedog-config
              - configMapRef:
                  name: dbm-env
              - secretRef:
                  name: storedog-secrets
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: dbm-scripts
              defaultMode: 0755
