apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    tags.datadoghq.com/env: ${DD_ENV}
    tags.datadoghq.com/service: store-db
    tags.datadoghq.com/version: "15.0"
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tags.datadoghq.com/env: ${DD_ENV}
        tags.datadoghq.com/service: store-db
        tags.datadoghq.com/version: "15.0"
      annotations:
        ad.datadoghq.com/postgres.logs: '[{"source": "postgresql", "auto_multi_line_detection":true}]'
        ad.datadoghq.com/postgres.checks: |
          {
            "postgres": {
            "init_config": {},
            "instances": [{"host":"%%host%%", "port":5432, "username":"datadog", "password":"datadog"}]
            }
          }
    spec:
      containers:
        - name: postgres
          image: ${REGISTRY_URL}/postgres:${SD_TAG}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-logs
              mountPath: /var/log/pg_log
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5       # Fast PostgreSQL startup
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 8          # 5s + (8 × 3s) = 29s max startup
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 3             # Faster checks for critical dependency
            timeoutSeconds: 2
            failureThreshold: 2          # Quick failure detection for load balancer
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 20            # Slightly more frequent for fast DB
            timeoutSeconds: 5            # Faster timeout for responsive DB
            failureThreshold: 3          # Less tolerant since DB is fast
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: postgres-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi