apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    tags.datadoghq.com/env: ${DD_ENV}
    tags.datadoghq.com/service: redis
    tags.datadoghq.com/version: "6.2"
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tags.datadoghq.com/env: ${DD_ENV}
        tags.datadoghq.com/service: redis
        tags.datadoghq.com/version: "6.2"
      annotations:
        ad.datadoghq.com/redis.logs: '[{"source": "redis"}]'
        ad.datadoghq.com/redis.checks: |
          {
            "redisdb": {
            "init_config": {},
            "instances": [{"host":"%%host%%", "port":6379}]
            }
          }
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          # Health probes optimized for fast Redis startup
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 2       # Redis starts in ~1-2s, minimal buffer for PV
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 8          # 2s + (8 × 2s) = 18s max startup
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 0       # Startup handles delay
            periodSeconds: 1             # Ultra-fast - Redis is critical dependency
            timeoutSeconds: 1
            failureThreshold: 2          # Fail fast if issues
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 0       # Startup handles delay
            periodSeconds: 20            # Moderate frequency for liveness
            timeoutSeconds: 3
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi