apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppeteer
  namespace: fake-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppeteer
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
        - name: puppeteer
          image: ${REGISTRY_URL}/puppeteer:${SD_TAG}
          env:
            - name: STOREDOG_URL
              # Updated to target frontend service directly instead of service-proxy
              value: "http://frontend.storedog.svc.cluster.local:3000"
            - name: PUPPETEER_TIMEOUT
              value: "30000"
            - name: SKIP_SESSION_CLOSE
              value: "false"
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "750m"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN  # Required for Puppeteer to run in Docker
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi  # Equivalent to shm_size: '4gb' in docker-compose