apiVersion: v1
kind: Service
metadata:
  name: dbm
spec:
  ports:
    - port: 7595
      targetPort: 7595
      name: http
  selector:
    app: dbm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbm
  template:
    metadata:
      labels:
        app: dbm
      annotations:
        ad.datadoghq.com/dbm.logs: '[{"source": "python"}]'
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: dbm
          image: ${REGISTRY_URL}/dbm:${SD_TAG}
          ports:
            - containerPort: 7595
          env:
            - name: FLASK_APP
              value: "dbm.py"
            - name: FLASK_DEBUG
              value: "0"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              value: postgres
            - name: DD_ENV
              value: ${DD_ENV}
            - name: DD_SERVICE
              value: storedog-dbm
            - name: DD_VERSION
              value: ${DD_VERSION_DBM}
            - name: DD_DBM_PROPAGATION_MODE
              value: full
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
