apiVersion: v1
kind: Service
metadata:
  name: ads-java
spec:
  ports:
    - port: 3030
      targetPort: 3030
      name: http
  selector:
    app: ads-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads-java
  template:
    metadata:
      labels:
        app: ads-java
    spec:
      containers:
        - name: ads-java
          image: ${REGISTRY_URL}/ads-java:${SD_TAG}
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
