apiVersion: v1
kind: Service
metadata:
  name: ads
spec:
  ports:
    - port: 3030
      targetPort: 3030
      name: http
  selector:
    app: ads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads
  labels:
    app: ads
    team: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads
  template:
    metadata:
      labels:
        app: ads
        team: advertisements
      annotations:
        ad.datadoghq.com/ads.logs: '[{"source": "python"}]'
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.37.0
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: ads
          image: localhost:5000/ads-python3:2.1.0
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
