apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        ad.datadoghq.com/backend.logs: '[{"source": "ruby", "auto_multi_line_detection":true}]'
    spec:
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: backend
          image: ${REGISTRY_URL}/backend:${SD_TAG}
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: REDIS_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: RAILS_ENV
            - name: DB_POOL
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_POOL
            - name: MAX_THREADS
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: MAX_THREADS
            - name: DD_ENV
              value: ${DD_ENV}
            - name: DD_SERVICE
              value: store-backend
            - name: DD_VERSION
              value: ${DD_VERSION_BACKEND}
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_ALLOCATION_ENABLED
              value: "true"
            - name: DD_PROFILING_TIMELINE_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
          # Health probes optimized for Rails application
          startupProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 3       # Very fast with init containers
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 5          # 3s + (5 × 2s) = 13s max startup
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 2             # Fast for API service
            timeoutSeconds: 1
            failureThreshold: 2
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 10            # Frequent for critical service
            timeoutSeconds: 5
            failureThreshold: 3