apiVersion: v1
kind: Service
metadata:
  name: discounts
spec:
  ports:
    - port: 2814
      targetPort: 2814
      name: http
  selector:
    app: discounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: discounts
          image: ${REGISTRY_URL-localhost:5000}/storedog-discounts:${SD_TAG-latest}
          ports:
            - containerPort: 2814
          command: ["flask", "run", "--port=2814", "--host=0.0.0.0"]
          env:
            - name: FLASK_APP
              value: "discounts.py"
            - name: FLASK_DEBUG
              value: "0"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              value: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
