apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: frontend-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
  labels:
    app: frontend-api
    team: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
        team: frontend
      annotations:
        ad.datadoghq.com/frontend.logs: '[{"source": "nodejs", "auto_multi_line_detection": true}]'
    spec:
      volumes:
        - name: feature-flags-config
          configMap:
            name: feature-flags-config
      initContainers:
        - name: wait-for-backend
          image: busybox:1.37.0
          command: ['sh', '-c', 'until nc -z backend 4000; do echo waiting for backend; sleep 2; done;']
      containers:
        - name: frontend-api
          image: localhost:5000/frontend:3.2.3
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NEXT_PUBLIC_ADS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_ADS_ROUTE
            - name: NEXT_PUBLIC_DISCOUNTS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_DISCOUNTS_ROUTE
            - name: NEXT_PUBLIC_DBM_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_DBM_ROUTE
            - name: NEXT_PUBLIC_FRONTEND_API_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_FRONTEND_API_ROUTE
            - name: NEXT_PUBLIC_SPREE_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_SPREE_API_HOST
            - name: NEXT_PUBLIC_SPREE_CLIENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_SPREE_CLIENT_HOST
            - name: NEXT_PUBLIC_SPREE_IMAGE_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_SPREE_IMAGE_HOST
            - name: NEXT_PUBLIC_SPREE_ALLOWED_IMAGE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_SPREE_ALLOWED_IMAGE_DOMAIN
            - name: NEXT_PUBLIC_DD_ENV
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_DD_ENV
            - name: NEXT_PUBLIC_DD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: dd_application_id
            - name: NEXT_PUBLIC_DD_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: dd_client_token
            - name: NEXT_PUBLIC_DD_SERVICE_FRONTEND
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_DD_SERVICE_FRONTEND
            - name: NEXT_PUBLIC_DD_VERSION_FRONTEND
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: NEXT_PUBLIC_DD_VERSION_FRONTEND
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          volumeMounts:
            - name: feature-flags-config
              mountPath: /app/featureFlags.config.json
              subPath: featureFlags.config.json
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
