apiVersion: v1
kind: Service
metadata:
  name: service-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: service-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-proxy
  template:
    metadata:
      labels:
        app: service-proxy
    spec:
      containers:
        - name: service-proxy
          image: ${REGISTRY_URL}/nginx:${SD_TAG}
          ports:
            - containerPort: 80
          env:
            - name: NGINX_RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
