apiVersion: v1
kind: Service
metadata:
  name: otelcol
spec:
  ports:
    - port: 4317
      targetPort: 4317
      name: grpc
      protocol: TCP
    - port: 4318
      targetPort: 4318
      name: http
      protocol: TCP
  selector:
    app: otelcol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
      annotations:
        ad.datadoghq.com/otelcol.logs: '[{"source": "otel"}]'
    spec:
      containers:
        - name: otelcol
          image: otel/opentelemetry-collector-contrib:0.130.0
          args:
            - "--config=/etc/otelcol-config.yaml"
          ports:
            - containerPort: 4317
              name: grpc
              protocol: TCP
            - containerPort: 4318
              name: http
              protocol: TCP
          env:
            - name: OTEL_LOG_LEVEL
              value: "debug"
            - name: DD_SITE
              value: ${DD_SITE}
            - name: DD_API_KEY
              value: ${DD_API_KEY}
            - name: DD_APP_KEY
              value: ${DD_APP_KEY}
            - name: DATADOG_API_KEY
              value: ${DATADOG_API_KEY}
            - name: DD_ENV
              value: ${DD_ENV}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - name: otelcol-config-ddog
              mountPath: /etc/otelcol-config.yaml
              subPath: otelcol-config.yaml
      volumes:
        - name: otelcol-config-ddog
          configMap:
            name: otelcol-config-ddog