apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        ad.datadoghq.com/worker.logs: '[{"source": "ruby", "auto_multi_line_detection":true}]'
    spec:
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: worker
          image: ${REGISTRY_URL}/backend:${SD_TAG}
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          env:
            - name: WORKER
              value: "true"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: REDIS_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_POOL
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_POOL
            - name: MAX_THREADS
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: MAX_THREADS
            - name: DD_ENV
              value: ${DD_ENV}
            - name: DD_SERVICE
              value: store-worker
            - name: DD_VERSION
              value: ${DD_VERSION_BACKEND}
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_ALLOCATION_ENABLED
              value: "true"
            - name: DD_PROFILING_TIMELINE_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
          # Health probes optimized for background worker
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "ps aux | grep '[s]idekiq' | grep -v grep"
            initialDelaySeconds: 8       # Fast worker startup with deps ready
            periodSeconds: 3             # Quick checks for background process
            timeoutSeconds: 3
            failureThreshold: 6          # 8s + (6 × 3s) = 26s max startup
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "ps aux | grep '[s]idekiq' | grep -v grep"
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 5             # More frequent monitoring
            timeoutSeconds: 3
            failureThreshold: 2          # Quick failure detection
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "ps aux | grep '[s]idekiq' | grep -v grep"
            initialDelaySeconds: 0       # Startup probe handles delay
            periodSeconds: 20            # More frequent for critical background worker
            timeoutSeconds: 8
            failureThreshold: 3          # Less tolerant for faster recovery