apiVersion: v1
kind: Service
metadata:
  name: ads
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads
  template:
    metadata:
      labels:
        app: ads
    spec:
      containers:
        - name: ads
          image: localhost:5000/storedog-ads:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
