apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: docker.io/hostpath
# If the above provisioner doesn't work, your Kubernetes environment may be different.
# For Minikube, try: k8s.io/minikube-hostpath
# For Kind, try: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
