apiVersion: v1
kind: ConfigMap
metadata:
  name: storedog-config
data:
  POSTGRES_USER: postgres
  DB_HOST: postgres
  DB_PORT: "5432"
  REDIS_URL: redis://redis:6379/0
  RAILS_ENV: production
  DB_POOL: "25"
  MAX_THREADS: "5"
  NEXT_PUBLIC_ADS_ROUTE: /services/ads
  NEXT_PUBLIC_DISCOUNTS_ROUTE: /services/discounts
  NEXT_PUBLIC_DBM_ROUTE: /services/dbm
  NEXT_PUBLIC_FRONTEND_API_ROUTE: http://localhost:3000
  NEXT_PUBLIC_SPREE_API_HOST: http://nginx/services/backend
  NEXT_PUBLIC_SPREE_CLIENT_HOST: /services/backend
  NEXT_PUBLIC_SPREE_IMAGE_HOST: /services/backend
  NEXT_PUBLIC_SPREE_ALLOWED_IMAGE_DOMAIN: nginx
