name: Discounts

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - services/discounts/**
  workflow_dispatch:
    branches: [ main ]

defaults:
  run:
    working-directory: discounts

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./services/discounts
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.PUBLIC_ECR_REGISTRY }}/storedog/discounts:latest

