name: Nginx

on:
  push:
    branches: [ main ]
    paths:
      - services/nginx/**
  workflow_dispatch:
    branches: [ main ]

defaults:
  run:
    working-directory: nginx

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: docker/login-action@v2.2.0
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.PUBLIC_ECR_REGISTRY }}/storedog/nginx:latest

