name: Publish release

permissions: {}

# Only release on a new tag that is a version number.
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish_service_containers:
    name: Publish all images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to GHCR
        id: login-ghcr
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download, Tag, and Push Service Images
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}

          IMAGES=(
            ghcr.io/datadog/storedog/backend
            ghcr.io/datadog/storedog/discounts
            ghcr.io/datadog/storedog/ads-python
            ghcr.io/datadog/storedog/ads-java
            ghcr.io/datadog/storedog/nginx
            ghcr.io/datadog/storedog/frontend
            ghcr.io/datadog/storedog/dbm
            ghcr.io/datadog/storedog/postgres
            ghcr.io/datadog/storedog/puppeteer
          )

          for i in "${IMAGES[@]}"
          do
            echo "$i"

            docker pull "$i":latest
            docker tag "$i":latest "$i":$TAG
            docker push "$i":$TAG

          done

          echo "All done"
